User.create!(username: "David1", email: "david1@example.com", password: "password1")
User.create!(username: "David2", email: "david2@example.com", password: "password2")
User.create!(username: "David3", email: "david3@example.com", password: "password3")
User.create!(username: "David4", email: "david4@example.com", password: "password4")
User.create!(username: "David5", email: "david5@example.com", password: "password5")
User.create!(username: "David6", email: "david7@example.com", password: "password7")
